server:
  port: 8086
  application:
    name: no-repeat
spring:
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:${mysql.port:3306}/testdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql.username:root}
    password: ${mysql.password:root}
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        default_value_generator: org.hibernate.id.enhanced.SequenceStyleGenerator
        default_sequence_name: students_seq

